package com.twitterapp.models;


/**
 * Tweet generated by hbm2java
 */
public class Tweet implements java.io.Serializable {

	private Integer tweetId;
	private User user;
	private String tweet;
	private String type;
	private int isConvo;

	public Tweet() {
	}

	public Tweet(User user, String tweet, String type, int isConvo) {
		this.user = user;
		this.tweet = tweet;
		this.type = type;
		this.isConvo = isConvo;
	}

	public Integer getTweetId() {
		return this.tweetId;
	}

	public void setTweetId(Integer tweetId) {
		this.tweetId = tweetId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTweet() {
		return this.tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getIsConvo() {
		return this.isConvo;
	}

	public void setIsConvo(int isConvo) {
		this.isConvo = isConvo;
	}

}
