package com.twitterapp.models;


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPassword;
	private Set tweets = new HashSet(0);

	public User() {
	}

	public User(String userName, String userPassword) {
		this.userName = userName;
		this.userPassword = userPassword;
	}

	public User(String userName, String userPassword, Set tweets) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.tweets = tweets;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Set getTweets() {
		return this.tweets;
	}

	public void setTweets(Set tweets) {
		this.tweets = tweets;
	}

}
